main: me.Nort721.Fly.SimpleFlyPlugin
version: 1.14
name: SimpleFlyPlugin
author: Nort721
description: the pefect fly plugin

commands:
  fly:
    description: enable/disable fly - main command
    permission: cmd.fly.use