# -+- Simple Fly Plugin By Nort721 v1.11 -+-
# placeholders:
# %player%

Messages settings:
  prefix: '&e&lFly >&r '
  enable fly message: '&b fly mode enabled for %player%'
  disable fly message: '&b fly mode disabled for %player%'
  enable fly message other (player message): '&b your fly mode has been enabled by %player%'
  disable fly message other (player message): '&b your fly mode has been disabled by %player%'
  enable fly message other (admin message): '&b you have enabled fly mode to %player% successfully'
  disable fly message other (admin message): '&b you have disabled fly mode to %player% successfully!'
  fly all enable message: '&eyou have &a&lenabled &efly mod for all the players on the server'
  fly all disable message: '&eyou have &c&ldisable &efly mod for all the players on the server'
  no money message: '&c&lYou do not have enough money for that!'
  no permissions message: '&7You do not have permissions to use this command'
  disabled world message: '&c&lThis plugin is disable in this world'
  reload config successfully: '&a&lconfig has been reloaded successfully'


Other settings:
  when player join fly is enabled/disabled/none: none


Economy settings:
  use economy: false
  take money for using fly command: false
  price for using fly command: 35


Sound & Particle effects:
  play particle effect while flying: true
  play sound when using fly command: true
  play sound when starting fly: true


Disable_worlds:
  - example