main: me.nort721.simpleflyplugin.SimpleFlyPlugin
version: 1.18
name: SimpleFlyPlugin
author: Nort721
description: the pefect fly plugin

commands:
  fly:
    description: main command
    permission: cmd.fly.use